### ISSUE TITLE
/ in note file names

### ISSUE THREAD

**Issue by CraigDamlo** [GitJournal/GitJournal#102]
If you have notes saved by title, and have a "/" in the title the file fails to update to the repository. If the filename is anything else, the "/" can be in the note title.

**Comment by vHanda** [comment]
Hey Craig.

I'm not sure what the expected behaviour should be - I was going to just not allow '/' in filenames, but I'm wondering if that's enough. Or should I be looking and seeing if the user is using that as a shortcut to move the note to an existing directory? What if the directory doesn't exist?

**Comment by CraigDamlo** [comment]
Fair point, I should have given a possible solution. The issue I had was the lack of error warning; the app created the note and then just deleted it durning sync. So at a minimum a warning would have been nice so I didn't lose the note. I only figured out what happed after a bunch of testing.

For my use case I would have rather had the filename changed by the app so that it didn't get deleted, but I could see the use case of pushing into a directory as well.

As a short term solution to avoid the loss of notes I would just not allow the "/" in the filename.
