### ISSUE TITLE
Improve 'title' handling

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#112]
Currently, we can have a 'title' in the YAML header as metadata. However, many markdown documents typically start with an h1 header containing the title, this makes displaying the document a bit strange as it then has two titles.

I propose to make this configurable. By default -
* We store the title as the h1 in the markdown document and do not store it in the YAML metadata. This would result in breaking the default behaviour.
* The default markdown editor has a section for 'title', this should update either the yaml metadata or the h1 of the markdown. Maybe make this configurable?

---
> Please vote on this issue with a 👍reaction. It's one of the primary mechanisms used to prioritize issues.

**Comment by jasonwilliams** [comment]
The more I think about this issue the more it makes sense to just use the h1 of the markdown file by default. (I’m ok with opt-out config though)

Why? Because GitHub, Gitlab, Bitbucket etc all do this and this app is supposed to be compatible with them, so it would seem odd for GitJournal to work in a different way.
If you create a new file the title should become the h1.

What is the yaml title used for? On my list I see file names so it’s not used in the browse view.

**Comment by vHanda** [comment]
> The more I think about this issue the more it makes sense to just use the h1 of the markdown file by default. (I’m ok with opt-out config though)
> 
> Why? Because GitHub, Gitlab, Bitbucket etc all do this and this app is supposed to be compatible with them, so it would seem odd for GitJournal to work in a different way.
> If you create a new file the title should become the h1.
> 
> What is the yaml title used for? On my list I see file names so it’s not used in the browse view.

I agree. I'm going to change that to be the default behavior.

**Comment by vHanda** [comment]
So the new default behaviour is as follows -

* When reading, the yaml metadata is given preference over h1
* When writing, the title is written in h1 instead of the yaml metadata

This way existing user's titles don't disappear. In the Settings one can still configure it to be written to the yaml header, instead - https://twitter.com/GitJournal_io/status/1288493317647368192
