### ISSUE TITLE
Files with / in the title disappear on upload

### ISSUE THREAD

**Issue by zacdemi** [GitJournal/GitJournal#132]
Device: IOS iphone SE
Version: 13.3.1
Reproduce: Create a file with a forward slash / in the title. Try to commit changes. File will not upload to git and disappear from app interface.

**Comment by mipro98** [comment]
This seems to be the same bug as #102. As far as I can see the commit (9a77afc) just handles file renames and disallows `/` in the new file name.

In fact, when the title contains a `/` the file is *not even created*, even though it appears as a normal note entry in the app (I checked the behavior by checking the files under `/data/data/io.gitjournal.gitjournal/files/journal`). When updating / pulling, the file seems to get deleted but actually the entry just disappears from the UI.

Possible solution:
So when file naming is set to be used from the title via settings, there should also be a check for invalid characters when creating a note. Since the title *might* contain valid slashes, I would suggest to transform the `/` into some valid character for the filename rather than forbidding slashes in titles.
