### ISSUE TITLE
discussion - how to handle merge conflicts?

### ISSUE THREAD

**Issue by aisbergde** [GitJournal/GitJournal#155]
A main idea of GitJournal is to use a Git repository.

That's way I wan't to start a discussion or to share experience how to handle merge conflict. I think, you are working for a long time on this project and I am sure you have some ideas regarding merge conflicts. Can you share your experience and ideas?

I love git and I try to use it when ever possible, in all my projects. That's why it would be naturally for me to use Git also for my notes system. (And I like to document in Wiki's using markdown, so a markdown based notes system is what I need.)

I am using windows and android. Using git on windows is easy, there is a lot of software to support: VS Code and Visual Studio have git support, but my favorite tool is TortoiseGit, ...

But when I started to fine something on android supporting git then it is not so easy. I found "mGIT", "Spck Code Editor / JS Sandbox / Git Client" and also "GitJournal". There are some other project but there is no current developement. Maybe there are some other tools?

The **main issue** I found when using **git on android are merge conflicts**. I did not find any easy way how to solve merge issues. mGIT did some kind of automatic merge not showing what are the sources - not what I want, spck only pointed out merge conflicts, i did not check very deeply, because it looks like the repositories are in a kind of sandbox. But in general it looks very interesting and can also support markdown files.

I tried to use a special branch for my android notes, this way the merge conflicts should or could not be solved on android but for example when GitHub is used:
- a Pull Request needs to be created (this is only possible in the desktop view of the website, it is not possible using the mobile view or an app, or I did not found how)
- the Pull Request needs to be processed, to merged, merge conflicts needs to be solved. This is possible when using the desktop but it is hard to do on mobile phone. 
- And all this together is to complicated. 

**How GitJournal plans to handle merge conflicts?**

My current solution is to use **OneDrive** to synchronize, but there are also issues:

- First I tried to use **FolderSync**, but instead of "ignoring" a conflict (there are some settings) sometimes (to often) it happened that a "newer" Android version just overwrites the "older" OneDrive Version, but the "older" OneDrive version was the version from my Desktop. The good thing is: there is a version control on each file in Ondrive, but you can't compare directly, you must download several files and compare them with some comparing tools.
- Now I use OneSync. I also get conflicts often, but at least OneSync will not overwrite files but instead it renames files and I have two of them:
  - todo.txt
  - todo (conflict 2020-05-30-11-39-14).txt
both files are synchronized also to my desktop, I can compare and merge them on my desktop, much more easy than on Android. The most important thing is: I will not lost information.

Using git with GitJournal I also should not lost information, if all changes will be commited. Both on android and on desktop. 

I see GitJournal will do a lot to avoid merge conflicts, syncing on startup, syncing on changes. This is great, much easier than using a separate git client.

But there *will be merge conflicts*, it is nearly not possible to avoid them always.

What are the GitJournal plans when these conflicts happen?
- a build in merge system?
- only messages about merge conflicts? How to solve them in this case?
- or like OneSync does: a copy of the conflicted file is created and put under version control?

I like the OneSync way to create a copy of the conflicted file because this is easy and nothing in lost and the conflict can be solved also on the desktop.

**Comment by vHanda** [comment]
Currently whenever GitJournal encounters a merge conflict it chooses the local changes over the remote changes. This isn't ideal, but since everything is in the history, no data is ever lost.

Moving forward, what I would like to do is -

1. Smarter auto-merge conflict resolution. Currently if one note has been edited outside of GitJournal and inside GitJournal, we don't even try to merge them together. In many cases, (maybe completely separate lines are modified, or just the YAML header is modified) we could apply many heuristics and find cases where we know what is the right thing to do.

2. Add a mode where un-resolvable merge conflicts are not automatically resolved, but stay in some kind on un-resolved state until the note is opened, and then require manual resolution. I'm not sure how this should be presented visually.

Currently (1) is blocked until I move the merging code from using `libgit2` to [`dart_git`](https://github.com/GitJournal/dart_git). With libgit2, doing this kind of conflict resolution would need to done in C, and a lot of logic would need to be reimplemented.

**Comment by aisbergde** [comment]
- choosing local versions most time (in my case) is the wrong version. 
I would lost instant access to all remotely done changes, a no go
- some heuristic todo an automatic merge not asking me is a no go too. If you build this then please also add an option to disable :-) 
- for me the pragmatic solution would be to keep both versions as different files so I can later merge manually or make a decision which to keep and which to use. I could do this on PC.

I can imagine to implement an conflict manager. If a conflict happens then both versions are shown in 2 windows parallel and I have these choices
- use remote
- use local
- Keep both and merge later
- here could be also shown some automatic merge suggestion. If you want to spent time on this. I would not if I would be the developer. Only if there would be some ready modules you could use.
- or something more complicated, but I would not spent too much resources

**Comment by derwok** [comment]
I see this releaxed. 

GitJournal does many atomic commits/syncs to Git. Always wenn you leave a file (Click "OK" checkmark) the git sync is happening immediately in the background. While on a real code base this would be not good (cluttering history). On a note taking system this mimics dropbox behaviour which I like.
Because on a note taking system history is more for backup reasons, not vor debugging, versioning, branching.

So with atomics syncs in place and a note taking system beeing more a "1 person" thing... 
I think merge conflicts are rather theoretical... You cant type on two keyboards at the same time.

My 2cts.

**Comment by aisbergde** [comment]
@derwok Thanks for your experience.

My experience is different, I have often lost information or data when working on different devices. That's why I love the idea to have the information at least in git.

I am often traveling and especially in the train in Germany the internet is often not so good. The normal issue is:

- I do something on the desktop, these changes are synchronized into the cloud (or into git)
- I start a mobile app when the internet is poor, the app can't get the latest state from the cloud
- I change something in the mobile app and when I am online later the mobile changes will be committed.

How I can access the older desktop version in this case? I would need a mobile git client, would need to compare and merge. This is hard to do or impossible on Android. 

That's why the normal way how Dropbox, OneDrive and Google Drive work does not work for me for files I use and change on different devices. These cloud services don't ask and I can't access both versions.

That's why I am happy that OneSync will not work the usual way to use the latest version, but it will create a copy and I have access to both versions.

That's why I hope to find a git based solution to be able to use some git features also on Android:
- access a different version
- get information about conflicts
- merge simple conflicts

**Comment by vHanda** [comment]
Closing this in favor of #241
