### ISSUE TITLE
Support '.markdown' extension

### ISSUE THREAD

**Issue by vHanda** [GitJournal/GitJournal#218]
We currently only support '.md' or '.txt'

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Please also subscribe to the issue if you're interested, as that way I can discuss possible implementations and share mockups.

**Comment by rgtk** [comment]
I second that.

Enforcing heuristics on file names makes it impossible for people with non-standard workflow to use this great app.

My personal knowledge base system doesn't use any file extensions for text files at all; and I cannot use GitJournal because of it.

The best option would be to make file filtering customizable (eg. via regexp pattern).

**Comment by vHanda** [comment]
Closing this in favor of #146. As the planned implementation will result in `.markdown` files also being supported.
