### ISSUE TITLE
Simple questions

### ISSUE THREAD

**Issue by benji88i** [GitJournal/GitJournal#379]
Hi there,

I have a few questions about the features of the app.

1. I enabled the "markdown toolbar" in advanced features but it doesn't seem to show. 
2. I try to add tags using the markdown shortcut codes mentioned in the settings (like @, #, +). It doesn't work.
3. If I allow the notes to be stored on the device does that mean it no longer syncs to the GitHub repository? 
4. What is the custom metatags used for in the yaml header

**Comment by vHanda** [comment]
Sorry. I missed this issue.

1 & 2. - The markdown toolbar is a bit broken. It's not the expected behaviour.
3. I'm not sure I follow - Once GitHub is setup it will always try to sync to it - Unless you explicitly disable the automatic syncing. In which case the cloud icon will show the number of unsynced changed.
4. Sorry. Could you elaborate?
