### ISSUE TITLE
Cloning fails if the default branch is not master.

### ISSUE THREAD

**Issue by brpaz** [GitJournal/GitJournal#418]
## Description

The default `master` branch is being renamed to `main` in most Git providers. It´s the default for new repos in GitHub. GitJournal is expecting the repository to have a master branch and fails to clone otherwise.

Maybe the user could have an option to select which branch he wants to clone in the GitJournal app?

**Comment by vHanda** [comment]
Hi. Could you please give me some instructions on how to reproduce this? GitJournal asks the provider what the default branch should be, and uses that.

**Comment by vHanda** [comment]
Hello. Could you please re-open this issue if it still occurs with version `1.74`?

**Comment by jasperslot** [comment]
Hello, I just started to use the app and having the same issue. I created a few notes in gitjournal, then created a new repo on GitHub. But now it doesn't work, since I get the error "GitRefNotFound: refs/remotes/origin/master". This is a valid error, since the new default branch name is "main". So, I tried to change the branch within gitjournal, but it only shows master... I am using gitjournal GitJournal 1.77.4+2602 on Android.
