### ISSUE TITLE
Inline tags

### ISSUE THREAD

**Issue by carstenwm** [GitJournal/GitJournal#44]
I don't know anything about how to do app's, but one thing I often miss in journal and diary apps is inline # tags and @persons.

And the possibility to use the Gitjournal as a Webpage  
Just throwing in what was on my mind - I love this app, thank you!! 

---
> Please vote on this issue with a 👍 reaction. It's one of the primary mechanisms used to prioritize issues. Also, if you subscribe to the issue you will notified about its progress, and get a chance to see mockups and discussions about the feature.

**Comment by vHanda** [comment]
Hey. Thanks for your suggestion. Let me first start with explicit tag support, and once that is done, adding inline tags would be trivial. 

I've filed another bug for tracking the web app #45. The Web version might take a while, since the underlying technology I'm using (Flutter) has just moved Web support to Beta, but there are still lots of bugs. Also, I'd have to change the backend substantially as one cannot use SSH in the browser. But it is something I also really want.

**Comment by aisbergde** [comment]
When you once will implement inline tags, please consider also to implement `+abc`

I use a todo.txt task management system and there are `+abc` and `@def` used and I use them also in my markdown notes.
