### ISSUE TITLE
YAML meta data 'type' being overwritten

### ISSUE THREAD

**Issue by iestynallcard** [GitJournal/GitJournal#567]
Hi there,

First and foremost, loving the App and please keep it up. I bought the App and wish to continue supporting your development efforts as I really think you are on to something.

I have discovered a bug which may stop me from using your App however.

I use Visual Studio Code with FOAM. I seem to be losing my “type” metatags in your app. I think it may have something to do with when you save and Parse the files?

I have had a metatag called type in your App, but it just seems to ignore it. 

Syntax I have used:

type : [Contact , Work, Personal]

It seems to work if the Metatag is Cased, as in “Type” versus “type”

Within FOAM the Meta data is really useful on large datasets, especially when you are viewing things in Work and want to keep things private. But uppercase Type is not seen.

I know I can work around this for the sake of your App,  but to be fair, the Graph in FOAM is awesome. I could use multiple Git repos etc

Also, The graph functionality in your APP doesn’t work properly, I move the Points around and the links go mental. Unusable at the moment, but its concept is great

**Comment by qcasey** [comment]
Similar to #374 

But I agree, using Dendron for VS Code this seems to have gotten worse over the last few months. Maybe I'm imagining it...

**Comment by vHanda** [comment]
@iestynallcard : Thanks.

The problem is that GitJournal internally uses the 'type' tag to store what kind of note is it - Journal / Normal / Checklist, which it then uses to choose the default editor to open for that note.

Is there any way Foam could be configured to use another field? If not, I guess I can provide a way for gitjournal to use something apart from 'type' to store that information.

**Comment by vHanda** [comment]
> But I agree, using Dendron for VS Code this seems to have gotten worse over the last few months. Maybe I'm imagining it...

Sadly there hasn't been a new release since October 12th. Google keeps rejecting my builds even though I've fixed the issue they raised. Plus the appeals seem to go into a black hole. It seems I'm going to need to post this on HackerNews or something.

Regarding Dendron getting worse, could you please file bugs for each case where it is removing the metadata? It's easier for me if there is a clean input file which I can just paste and try out.
