### ISSUE TITLE
Exception: Type cannot be converted to Protobuf Union - Null

### ISSUE THREAD

**Issue by Maatteogekko** [GitJournal/GitJournal#580]
I am trying out this app together with a [Dendron vault](https://wiki.dendron.so/notes/6682fca0-65ed-402c-8634-94cd51463cc4/). There are some minor inconveniences, like the metadata header not being created the same way, but nothing major.
After doing some modifications on Dendron and having pushed the changes to the repository used by GitJournal, and pulling them from the app (on android), I get this exception: `Exception: Type cannot be converted to Protobuf Union - Null`

It doesn't seem to break anything, so I am wondering what is causing it.
Please let me know what you need to debug this, or if you prefer I can try to look into this myself, and maybe implement some things that would make working with Dendron a better experience.

PS: Love the app! 💙 I really want to make it fit inside my workflow.

**Comment by vHanda** [comment]
Sorry about this, it's fixed in git, but I haven't yet made a release because of a performance problem when storing the repo in an external directory. (I've added a check for new/modified files on start, but that's harming the boot speed considerably - over 1-2 seconds).

You can access the latest dev version from fdroid - https://gitjournal.io/fdroid . I'll try to make a release today.
