### ISSUE TITLE
Web address using for sync

### ISSUE THREAD

**Issue by Devamitta** [GitJournal/GitJournal#622]
We have a restricted internet, where we allow only some websites.

GitHub.com is whitelisted

And GitHub Mobile app is working well, but GitJournal write an error when I am trying to sync : 
GitException: failed to connect to GitHub.com connection refused.

Which web address we have to add to whitelist to make this app sync?

**Comment by Devamitta** [comment]
Currently, we are whitelisted all what is necessary for GitHub.

github-cloud.s3.amazonaws.com
*.github.com
*.githubassets.com
*.githubusercontent.com
*.octocaptcha.com
*.github.dev
*.ghcr.io
*.github.io

What else this app GitJournal uses for sync?

**Comment by vHanda** [comment]
Sorry for the huge delay.

For GitJournal, the only required API would be your Git Host, which in this case is GitHub. So port 22 on github.com.

Otherwise the only other communication is to Sentry for crash reports and a custom server for Analytics (both of these can be disabled in the settings). But GitJournal will work perfectly regardless.

Does this answer your question?

**Comment by vHanda** [comment]
Please feel free to reopen this if you have more questions.
