### ISSUE TITLE
Desktop Downloads

### ISSUE THREAD

**Issue by sbstnx0** [GitJournal/GitJournal#946]
Please add download links for the macOS, Linux, and Android binaries of GitJournal to the GitJournal website. It would be really helpful, instead of having to compile the program ourselves.

**Comment by vHanda** [comment]
I currently have no plans for releasing the desktop version of Gitjournal. The UI really only works well for mobiles, and the complexities of managing 3 additional platforms + code signing+ sandboxing is way too much.

Especially since a lot of code needs to be cross compiled.

I do plan to release a web version in the future, though. But it is very very far from being ready.
